version: "1.0"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: expense-tracker
    container_name: expense-tracker-backend
    command: npm start
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    image: expense-tracker
    container_name: expense-tracker-frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  data-volume: 
  node_modules:
  web-root:
    driver: local