name: Deploy Application

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build backend image
        run: docker build -t vdsavla21/expense-tracker-backend ./backend

      - name: 'Create env file'
        run: |
          touch ./backend/.env
          echo SECRET=${{ secrets.SECRET }} >> ./backend/.env
          echo MONGODB_URL=${{ secrets.MONGO_DB_URL }} >> ./backend/.env
          echo PORT=${{ secrets.PORT }} >> ./backend/.env
          

      - name: Publish Image to docker hub
        run: docker push vdsavla21/expense-tracker-backend:latest

      - name: Build and push frontend image
        run: docker build -t vdsavla21/expense-tracker-frontend ./frontend --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'

      - name: Publish Image to docker hub
        run: docker push vdsavla21/expense-tracker-frontend:latest
      
      
      - name: Deploy to EC2
        run: |
          # Pull the latest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:latest

          # Stop and remove existing containers if they exist
          docker stop expense-tracker-frontend || true
          docker stop expense-tracker-backend || true
          docker rm expense-tracker-frontend || true
          docker rm expense-tracker-backend || true

          # Run the new containers
          

          docker run -d --name expense-tracker-backend \
            -p 5000:5000 \
            -e PORT=${{ secrets.PORT }} \
            -e MONGODB_URL=${{ secrets.MONGO_DB_URL }} \
            -e SECRET=${{ secrets.SECRET }} \
            vdsavla21/expense-tracker-backend:latest

          docker run -d --name expense-tracker-frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:latest
